#!/usr/bin/env ruby

require 'find'
require 'rubygems'
require File.join(File.dirname(__FILE__), 'progress_bar')
require File.join(File.dirname(__FILE__), 'file_parser')

current_dir=File.expand_path(ARGV[0] || Dir.pwd)

puts "Looking for incorrectly named files in #{current_dir}"

no_matches=[]

Find.find(current_dir) do |path|
  if not FileTest.directory?(path) and path =~ /.mp3$/i
    data = FileParser.new(path)

    unless data.ignored?
      if not data.matches?
        no_matches << path
      end
    end
  end
end

if no_matches.size > 0 
	puts "\n\nNo Matches Found:"
	no_matches.each do |path|
		puts path
	end
end
